# Generated by Django 3.0.6 on 2020-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('mail_response', models.CharField(blank=True, max_length=255, null=True)),
                ('priem_data', models.DateField()),
                ('priem_fio', models.CharField(max_length=255)),
                ('priem_doljnost', models.CharField(max_length=255)),
                ('priem_content', models.TextField(blank=True, null=True)),
                ('priem_results', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('data_prinytiy', models.DateField()),
                ('number', models.IntegerField()),
                ('created_fio', models.CharField(max_length=255)),
                ('created_doljnost', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
